import fs from'node:fs';
import assert from'node:assert/strict';
import{SCHEMA_VERSION,SESSION_IDS,emptyState,estimate1RM,detectRecords,migrateState,mergeStateData,computeStats,exerciseVisible,exerciseRequired,resolvePrescription,startNextRound}from'../assets/logic.mjs';

const plan=JSON.parse(fs.readFileSync(new URL('../data/plan.json',import.meta.url),'utf8'));
const ok=(label,fn)=>{fn();console.log(`✓ ${label}`)};
const session=id=>plan.sessions.find(x=>x.id===id);
const exercise=(sid,id)=>session(sid).exercises.find(x=>x.id===id);

ok('schema 4, V3.3 revision, and 13 weeks',()=>{assert.equal(SCHEMA_VERSION,4);assert.equal(plan.schemaVersion,4);assert.equal(plan.planRevision,'3.3-multi-round');assert.equal(plan.weeks.length,13)});
ok('four sessions, primers, abs and optional core',()=>{assert.deepEqual(plan.sessions.map(x=>x.id),SESSION_IDS);for(const s of plan.sessions){assert.ok(s.primer);assert.ok(s.abs);assert.ok(s.core)}});
ok('B1 order includes Bulgarian split squat and adductor work',()=>{assert.deepEqual(session('B1').exercises.map(x=>x.id).slice(0,4),['b1-squat','b1-rdl','b1-bulgarian','b1-adductor'])});
ok('B2 order includes deadlift, front squat, reverse lunge and curl',()=>{assert.deepEqual(session('B2').exercises.map(x=>x.id).slice(0,4),['b2-deadlift','b2-front-squat','b2-reverse-lunge','b2-curl'])});
ok('B1 and B2 each contain middle and rear delt work',()=>{for(const id of['B1','B2']){const s=session(id);assert.equal(s.exercises.filter(x=>x.canonicalExerciseId==='lateral-raise').length,1);assert.equal(s.exercises.filter(x=>x.canonicalExerciseId==='rear-delt').length,1)}});
ok('single-leg and adductor work become optional when tired',()=>{for(const ex of[exercise('B1','b1-bulgarian'),exercise('B1','b1-adductor'),exercise('B2','b2-reverse-lunge')]){assert.equal(exerciseRequired(ex,'hypertrophy',1,'good'),true);assert.equal(exerciseRequired(ex,'hypertrophy',1,'tired'),false)}});
ok('W13 hides added lower-body accessories',()=>{for(const ex of[exercise('B1','b1-rdl'),exercise('B1','b1-bulgarian'),exercise('B1','b1-adductor'),exercise('B2','b2-front-squat'),exercise('B2','b2-reverse-lunge'),exercise('B2','b2-curl')])assert.equal(exerciseVisible(ex,'checkpoint'),false)});
ok('fatigue reduces the second compound by one set',()=>{const rule=plan.weeks.find(x=>x.week===7);assert.equal(resolvePrescription(exercise('B1','b1-rdl'),{phaseId:'deadlift-strength',week:7,rule,readiness:'good'}).sets,2);assert.equal(resolvePrescription(exercise('B1','b1-rdl'),{phaseId:'deadlift-strength',week:7,rule,readiness:'tired'}).sets,1);assert.equal(resolvePrescription(exercise('B2','b2-front-squat'),{phaseId:'deadlift-strength',week:7,rule,readiness:'tired'}).sets,1)});
ok('finishers offer exactly four choices and are not exercises',()=>{for(const id of['B1','B2']){assert.deepEqual(plan.finisherMenus[id].map(x=>x.id),['leg-press','hack-squat','leg-extension','calf-raise']);assert.ok(session(id).exercises.every(x=>x.phaseRole!=='finisher'))}});
ok('W4 and W9 are explicit deload weeks',()=>{assert.match(plan.weeks.find(x=>x.week===4).label,/减载/);assert.match(plan.weeks.find(x=>x.week===9).label,/减载/)});
ok('no landmine defaults or direct arm isolation',()=>{const names=plan.sessions.flatMap(s=>[s.primer,...s.exercises]).map(x=>x.name).join(' ');assert.doesNotMatch(names,/地雷管|二头弯举|三头下压|绳索下压/)});
ok('every planned movement exposes detail and demo URL',()=>{for(const s of plan.sessions)for(const ex of[s.primer,...s.exercises]){assert.ok(ex.canonicalExerciseId);assert.ok(ex.variantId);assert.ok(ex.phaseRole);assert.ok(ex.details?.setup);assert.ok(ex.details?.stop);assert.match(ex.demoUrl,/^https:\/\//)}});

const fresh=emptyState('2026-01-01T00:00:00.000Z');
ok('fresh state starts Round 1 without legacy migration',()=>{assert.equal(fresh.schemaVersion,4);assert.equal(fresh.activeRoundId,'round-1');assert.equal(fresh.rounds[0].currentWeek,1);assert.equal(migrateState({schemaVersion:3,logs:[{id:'old'}]}).logs.length,0)});
ok('same week and session can coexist across rounds',()=>{const data=emptyState();data.completions.push({id:'round-1:w1-A1',roundId:'round-1',week:1,session:'A1'});data.rounds[0].currentWeek=13;const next=startNextRound(data);data.completions.push({id:`${next.id}:w1-A1`,roundId:next.id,week:1,session:'A1'});assert.equal(new Set(data.completions.map(x=>x.id)).size,2)});
ok('new round is blocked before W13 and preserves history at W13',()=>{const data=emptyState();assert.equal(startNextRound(data),null);data.rounds[0].currentWeek=13;data.completions.push({id:'round-1:w1-A1',roundId:'round-1',week:1,session:'A1'});const next=startNextRound(data,'2026-04-01T00:00:00.000Z');assert.equal(next.number,2);assert.equal(data.completions.length,1);assert.equal(data.rounds[0].status,'completed')});
ok('full training weeks carry streak across rounds and deload weeks',()=>{const data=emptyState();for(let w=1;w<=13;w++)for(const s of SESSION_IDS)data.completions.push({id:`round-1:w${w}-${s}`,roundId:'round-1',week:w,session:s});data.rounds[0].currentWeek=13;startNextRound(data);for(const s of SESSION_IDS)data.completions.push({id:`round-2:w1-${s}`,roundId:'round-2',week:1,session:s});const stats=computeStats(data);assert.equal(stats.streak,14);assert.equal(stats.maxStreak,14);assert.equal(stats.fullWeeks.length,14)});
ok('an incomplete passed week breaks current streak but preserves maximum',()=>{const data=emptyState();for(const s of SESSION_IDS)data.completions.push({id:`round-1:w1-${s}`,roundId:'round-1',week:1,session:s});data.rounds[0].currentWeek=3;for(const s of SESSION_IDS)data.completions.push({id:`round-1:w3-${s}`,roundId:'round-1',week:3,session:s});const stats=computeStats(data);assert.equal(stats.streak,1);assert.equal(stats.maxStreak,1)});

const base={id:'r1',type:'main',qualityPassed:true,canonicalExerciseId:'deadlift',variantId:'conventional-deadlift',completionId:'round-1:w1-B2',exercise:'传统杠铃硬拉',weight:75,reps:'3',rpe:8,e1rm:estimate1RM(75,3)};
ok('records compare across rounds',()=>{const x={...base,id:'r2',completionId:'round-2:w1-B2',roundId:'round-2',weight:80,e1rm:estimate1RM(80,3)},result=detectRecords(x,[base]);assert.ok(result.types.includes('weight'));assert.ok(result.types.includes('e1rm'))});
ok('same-weight rep PR and variants remain independent',()=>{const old={...base,weight:80,reps:'3',e1rm:estimate1RM(80,3)},x={...base,id:'r2',completionId:'round-2:w2-B2',weight:80,reps:'5',e1rm:estimate1RM(80,5)};assert.ok(detectRecords(x,[old]).types.includes('reps'));assert.deepEqual(detectRecords({...x,variantId:'trap-bar-deadlift'},[old]).types,['first'])});
ok('PR XP is deduplicated by stored event list',()=>{const data=emptyState();data.prEvents=[{id:'round-1:w1-B2:deadlift:pr',xp:30}];assert.equal(computeStats(data).prXp,30)});
ok('backup restore and repeated import preserve rounds without duplicate rewards',()=>{const backup=emptyState();backup.rounds[0].currentWeek=13;startNextRound(backup);backup.completions=[{id:'round-1:w1-A1',roundId:'round-1',week:1,session:'A1'}];backup.prEvents=[{id:'pr-1',xp:30}];const restored=mergeStateData(emptyState(),backup),again=mergeStateData(restored,backup);assert.equal(restored.activeRoundId,'round-2');assert.equal(again.rounds.length,2);assert.equal(again.completions.length,1);assert.equal(again.prEvents.length,1);assert.equal(computeStats(again).prXp,30)});
